version: "3"

services:
  funkwhale:
    container_name: funkwhale
    restart: unless-stopped
    # add the version number in your .env file, or hardcode it
    image: funkwhale/all-in-one:0.20.1
    environment:
      # adapt to the pid/gid that own /srv/funkwhale/data
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data
      #- /path/to/your/music/dir:/music:ro
    ports:
      - 5000:80
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.funkwhale.rule=Host(`funkwhale.domain.com`)"
      - "traefik.http.routers.funkwhale.entrypoints=websecure"
      - "traefik.http.routers.funkwhale.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.funkwhale.loadbalancer.server.port=80"
networks:
  traefik_web:
    external: true

