version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    networks:
     - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.openvpn.rule=Host(`vpn.domain.com`)"
      - "traefik.http.routers.openvpn.entrypoints=websecure"
      - "traefik.http.routers.openvpn.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.openvpn.loadbalancer.server.port=80"

networks:
  traefik_web:
    external: true

